import React, { Component } from 'react';
import './audio_detector.css';
import videoBackground from './purple.mp4'; // Update the path to your video file
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faMicrophone } from '@fortawesome/free-solid-svg-icons';

export class AudioDetector extends Component {
  constructor(props) {
    super(props);
    this.state = {
      file: null,
      result: null
    };
  }

  componentDidMount() {
    document.body.classList.add('hide-footer'); // Add class to hide footer on this page
  }

  componentWillUnmount() {
    document.body.classList.remove('hide-footer'); // Remove class when component unmounts
  }

  handleFileChange = (event) => {
    this.setState({
      file: event.target.files[0]
    });
  };

  handleShowResult = () => {
    // Perform the AI detection for audio here and update the 'result' state
    console.log('Detecting if AI or not...');
  };

  handleMicrophoneClick = () => {
    document.getElementById('fileInput').click(); // Trigger click event of file input
  };

  render() {
    return (
      <div className="video-container">
        <video className="video-background" autoPlay loop muted>
          <source src={videoBackground} type="video/mp4" />
          Your browser does not support the video tag.
        </video>

        <div className="title-section">
          <h2>Detect if Your Audio is AI-Generated or Not</h2>
        </div>

        <div className="text-section">
          <h2>Real OR Fake Audio ?!</h2>
          <p>
            Our audio identification system effortlessly distinguishes between audio crafted by humans and those generated by AI. Using cutting-edge machine learning models, it meticulously examines various audio features like frequency, tempo, and spectral characteristics. By comparing these features to known patterns in both human and AI-generated audio, our system accurately determines the origin of each audio file.
          </p>
          <p>
            These machine learning models were trained on a vast dataset containing labeled audio files, allowing them to learn the subtle differences between human and AI-generated audio with ease. Through this training process, our system became adept at identifying the telltale signs of both human and AI craftsmanship, ensuring reliable classification results.
          </p>
        </div>

        <div className="upload-section">
          <h2 className='audioTitle'>Audio Analysis Area</h2>
          <div className="upload-frame">
            <input id="fileInput" type="file" accept="audio/*" onChange={this.handleFileChange} style={{ display: 'none' }} />
            <label htmlFor="fileInput" className="file-input-label">
              <FontAwesomeIcon icon={faMicrophone} onClick={this.handleMicrophoneClick} className="microphone-icon" />
            </label>
            <button onClick={this.handleShowResult} className='buttonn'>Show The Result</button>
          </div>
        </div>
      </div>
    );
  }
}

export default AudioDetector;
