# Generated by Django 5.0.2 on 2024-04-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0005_alter_user_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "plan_id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("plan_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("size_limit", models.IntegerField()),
                ("attempts_limits", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("history_limit", models.IntegerField()),
            ],
        ),
    ]
