# Generated by Django 5.0.2 on 2024-04-22 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0006_subscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
