# Generated by Django 5.0.2 on 2024-04-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0007_delete_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("size_limit", models.IntegerField()),
                ("attempts_limits", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("history_limit", models.IntegerField()),
            ],
        ),
    ]
