# Generated by Django 5.0.2 on 2024-04-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ai_media_detection",
            "0011_alter_datahistory_audio_alter_datahistory_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahistory",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="media/None/audio"),
        ),
        migrations.AlterField(
            model_name="datahistory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/None/image"
            ),
        ),
    ]
