# Generated by Django 5.0.2 on 2024-04-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0013_alter_datahistory_audio_alter_datahistory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahistory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="False/image"),
        ),
    ]
