# Generated by Django 5.0.1 on 2024-05-29 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0019_admin_image_admin_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="permission",
        ),
    ]
