# Generated by Django 5.0.1 on 2024-10-18 21:26

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                ("role", models.CharField(default="staff", max_length=50)),
                (
                    "image",
                    models.ImageField(
                        default="default.png",
                        upload_to=users.models.user_directory_path,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("reset_code", models.CharField(blank=True, max_length=50, null=True)),
                ("reset_expire", models.DateTimeField(blank=True, null=True)),
                ("is_team_member", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=100, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                ("social_links", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AnonymousAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=40)),
                ("attempts_left", models.PositiveIntegerField(default=5)),
                (
                    "last_attempt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("size_limit", models.IntegerField()),
                ("attempts_limits", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("history_limit", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("country", models.CharField(max_length=100)),
                ("is_activated", models.BooleanField(default=False)),
                ("subscription_start_date", models.DateField(blank=True, null=True)),
                ("subscription_end_date", models.DateField(blank=True, null=True)),
                ("remain_attempts", models.IntegerField(default=5)),
                (
                    "image",
                    models.ImageField(
                        default="default.png",
                        upload_to=users.models.user_directory_path,
                    ),
                ),
                ("reset_code", models.CharField(blank=True, max_length=50, null=True)),
                ("reset_expire", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=users.models.user_directory_path,
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=users.models.user_directory_path,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "attemptTime",
                    models.CharField(
                        blank=True,
                        default="19/10/2024 12:26 AM",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("modelResult", models.CharField(max_length=100)),
                ("media_size", models.CharField(default="0 KB", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
            options={
                "ordering": ["-attemptTime"],
            },
        ),
    ]
