# Generated by Django 5.0.1 on 2024-10-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahistory",
            name="attemptTime",
            field=models.CharField(
                blank=True, default="19/10/2024 12:27 AM", max_length=50, null=True
            ),
        ),
    ]
