# Generated by Django 5.0.1 on 2024-06-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_admin_datahistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
