# Generated by Django 5.0.1 on 2024-06-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_is_active_users_is_activated"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="reset_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="reset_expire",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
