# Generated by Django 5.0.1 on 2024-06-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_users_reset_code_users_reset_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahistory",
            name="media_size",
            field=models.CharField(default="0 KB", max_length=100),
        ),
    ]
