# Generated by Django 5.0.1 on 2024-06-20 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_anonymousattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAttempt",
        ),
    ]
