# Generated by Django 5.0.1 on 2024-07-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_delete_userattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="social_links",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="admin",
            name="sub_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
