# Generated by Django 5.0.1 on 2024-07-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_admin_is_active_admin_is_team_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="social_links",
            field=models.TextField(blank=True, null=True),
        ),
    ]
