# Generated by Django 5.0.1 on 2024-07-04 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_admin_social_links"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin",
            old_name="sub_title",
            new_name="subtitle",
        ),
    ]
