# Generated by Django 5.0.1 on 2024-07-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_rename_sub_title_admin_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahistory",
            name="attemptTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
