# Generated by Django 5.0.1 on 2024-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_datahistory_attempttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahistory",
            name="attemptTime",
            field=models.CharField(
                blank=True, default="08/07/2024 11:07 PM", max_length=50, null=True
            ),
        ),
    ]
