# Generated by Django 5.0.1 on 2024-07-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_datahistory_attempttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahistory",
            name="attemptTime",
            field=models.CharField(
                blank=True, default="08/07/2024 09:14 PM", max_length=50, null=True
            ),
        ),
    ]
