# Generated by Django 5.0.1 on 2024-07-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_datahistory_attempttime"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="datahistory",
            name="attemptTime",
            field=models.CharField(
                blank=True, default="09/07/2024 03:49 PM", max_length=50, null=True
            ),
        ),
    ]
