# Generated by Django 5.0.1 on 2024-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_admin_order_alter_datahistory_attempttime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="datahistory",
            name="attemptTime",
            field=models.CharField(
                blank=True, default="09/07/2024 03:54 PM", max_length=50, null=True
            ),
        ),
    ]
