# Generated by Django 5.0.2 on 2024-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0002_alter_user_remain_attempts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.IntegerField(null=True),
        ),
    ]
