# Generated by Django 5.0.2 on 2024-04-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0003_alter_user_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
