# Generated by Django 5.0.2 on 2024-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0004_alter_user_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscription_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
