# Generated by Django 5.0.2 on 2024-04-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0009_alter_user_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="media/image/None")),
                ("audio", models.FileField(upload_to="media/audio/None")),
                ("text", models.TextField()),
                ("attemptTime", models.DateTimeField(auto_now_add=True)),
                ("modelResult", models.CharField(max_length=100)),
                ("media_size", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_media_detection.user",
                    ),
                ),
            ],
        ),
    ]
