# Generated by Django 5.0.2 on 2024-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0010_datahistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahistory",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="media/audio/None"),
        ),
        migrations.AlterField(
            model_name="datahistory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/image/None"
            ),
        ),
        migrations.AlterField(
            model_name="datahistory",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
