# Generated by Django 5.0.2 on 2024-04-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0012_alter_datahistory_audio_alter_datahistory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahistory",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="None/audio"),
        ),
        migrations.AlterField(
            model_name="datahistory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="None/image"),
        ),
    ]
