# Generated by Django 5.0.2 on 2024-04-22 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ai_media_detection",
            "0015_rename_user_users_rename_name_datahistory_media_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datahistory",
            options={"ordering": ["-attemptTime"]},
        ),
    ]
