# Generated by Django 5.0.1 on 2024-05-03 08:29

import ai_media_detection.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0017_alter_users_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="image",
            field=models.ImageField(
                default="default.png",
                upload_to=ai_media_detection.models.user_directory_path,
            ),
        ),
    ]
