# Generated by Django 5.0.1 on 2024-05-29 15:55

import ai_media_detection.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_media_detection", "0018_users_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="image",
            field=models.ImageField(
                default="default.png",
                upload_to=ai_media_detection.models.user_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="role",
            field=models.CharField(default="staff", max_length=50),
        ),
    ]
